### ISSUE TITLE
SampleSheet2openBIS.sh with CRLF line endings on MiSeq1 after pull from GitHub

### ISSUE THREAD

**Issue by sschmutz** [medvir/DMS#10]
After pulling a new version from GitHub, the script `SampleSheet2openBIS.sh` is configured with CRLF line endings (which won't work). Only seems to occur on MiSeq1.
This issue can be _fixed_ when the file is opened in Atom and the line endings changed manually to LF (bottom right). But will reoccur when a new version is pulled from GitHub.
@ozagordi also looked into this previously and as far as I can remember no good explanation and/or fix was found. Therefore I suggest the Label _wontfix_ for this issue.

> WONTFIX The problem described is a bug which will never be fixed.

[Bug Status WONTFIX](https://en.opensuse.org/Bug_Status_WONTFIX)

**Comment by ozagordi** [comment]
This was actually fixed by following [this](https://help.github.com/articles/dealing-with-line-endings/#platform-windows).
