### ISSUE TITLE
Definition of genes/sequences included in the ambiguity score 

### ISSUE THREAD

**Issue by mihuber** [medvir/DMS#12]
The question arose on which genes the ambiguity score is calculated. Also env sequences might be included in a sample, however, the ambiquity score should only be calculated on pol genes.
Further, in the reports there are sometimes several caculations (for several contigs with coverage above threshold I assume). I think we also need to clarify this.

**Comment by ozagordi** [comment]
This issue belongs to MinVar, not to DMS. Please move it there.
