### ISSUE TITLE
Automate SampleSheet2openBIS.sh script at the end of a run.

### ISSUE THREAD

**Issue by mihuber** [medvir/DMS#14]
The only manual thing remaining at the end of a run is the double-clicking of the backup icon. If automated, runs finishing on the weekend or at night would already start the analysis pipeline or data would be accessible on the server.

A script could execute `SampleSheet2openBIS.sh` every hour, however, skip if there is an `/Illumina/MiSeqOutput/*/Data/Intensities/BaseCalls` directory without any `.fastq.gz` files (this would be a sign that a sequencing run is still in progress and not yet analyzed).

**Comment by ozagordi** [comment]
We already explored this possibility in the past. I contacted Illumina technical support last May, but from their response I could not infer a reliable way to automate this last step. The risk I see is that the script is executed while the `fastq.gz` are being written. In the most general case the script will see a folder with some complete files, one incomplete file, and some missing files. This will result in a number of unspecified and unpredictable errors.

I copy the conversation with tech support here below.

>Hello.
I work at at the Institute of Medical Virology, University of Zurich, where we operate two Illumina MiSeq instruments. We are trying to set up an automatic transfer of data from the MiSeq system to a local server for analysis and storage.
>I have been looking a specific event from which it can be inferred that all fastq files have been generated and saved in Illumina/MiSeqOutput/ I have noticed that GenerateFASTQRunStatistics.xml and CompletedJobInfo.xml are create at the same time of the fastq files (see attachment). Is this a reliable way to infer that the generation of all fastq files is complete? My idea was to set up a script that monitors the run folders in Illumina/MiSeqOutput/ and only tries to copy those where CompletedJobInfo.xml (or GenerateFASTQRunStatistics.xml) are present. Could you please confirm this?
>Kindest regards,

>Dear Osvaldo,
>Thank you for contacting Illumina Technical Support with your inquiry.
>There is no such file that pops up when all the fastq files have been generated.
>I think the best thing for you to do is to set up MCS to save the output data in your server location (just copy the path to the server location in the data output path)  and to set up MSR so that it saves the data on the server as well. Please see attached document on how to do this.
>This way, you will have the data on your instrument and on the server location.
>You would only need to repeat the MSR procedure if you update the software, otherwise the data will automatically be stored on the server for each run.
>Best regards,

**Comment by sschmutz** [comment]
Using screen-sharing and double-click from remote could solve some of the "issues". But I'm not sure if you'd like to support working (or having something to do with work) from outside the IMV.

Pros:
- able to check if sequencing run has finished successfully
- possible to check if there was no mistake during demultiplexing before synchronizing

Cons:
- not automated, just a bypass
- security?

**Comment by sschmutz** [comment]
This was addressed by adding a backup script with a delay of 17h.
One can now execute the `backup-delayed` script as soon as a 150 cycles run is started.
see commit 5a1c13b73f1ea39985b71ec60df1800d5743ff6e
