### ISSUE TITLE
Backup2timavo missing in DMS repo?!

### ISSUE THREAD

**Issue by sschmutz** [medvir/DMS#17]
We only have that script on the MiSeqs?

**Comment by sschmutz** [comment]
I think I got confused, because `DMS/MiSeqScripts/backup2nc.sh` is there (which we could remove) but Backup2timavo runs `DMS/openBIS/SampleSheet2openBIS.sh`
Should we document this:
`C:\cygwin64\bin\mintty.exe -e /bin/sh -l -c ' /cygdrive/c/Users/sbsuser/DMS/openBIS/SampleSheet2openBIS.sh &>> /home/sbsuser/backup2timavo.log'`

**Comment by ozagordi** [comment]
Please see the wiki [page](https://github.com/medvir/DMS/wiki/Data-producers:-MiSeq-1-and-MiSeq-2). I'd say one could expand from there. One more thing to document is that the home folder where one lands with Terminal is different from the home of cmder. The scripts and log files are immediately found with Terminal, the GitHub repo to clone with git is found with cmder (which has git included).

**Comment by sschmutz** [comment]
Closed with revision of `Data producers: MiSeq 1 and MiSeq 2` [wiki](https://github.com/medvir/DMS/wiki/Data-producers:-MiSeq-1-and-MiSeq-2).
