### ISSUE TITLE
mapping_pybis_script.py aborts if samples cannot be matched in one project.

### ISSUE THREAD

**Issue by mihuber** [medvir/DMS#18]
The MISEQ_RUN `181025_M02081_0335_000000000-C5N2B` was not registered (for as yet unknown reasons). The MISEQ_SAMPLES could therefore not be matched. See `pybis_script.log`

> INFO 2018/10/29 08:00:10: general_mapping() 82: 	Found 20 unmapped MISEQ samples in project ANTIBODIES

The script did not proceed to the other projects and e.g. resistance samples were not matched and not analysed. The script should ideally give a noticeable error message and continue to the other projects.

**Comment by ozagordi** [comment]
What is the error message? There should also be other log/err files in the
home on nevoso. That’s just the last info message in the log.
-- 
Sent from a mobile device. Please excuse any typos.

**Comment by mihuber** [comment]
Update: The run `181025_M02081_0335_000000000-C5N2B` has 71 samples. According to the `backup2timavo.log` on the MiSeq, for all 71 samples and as well as the run a properties file is written in the project antibodies. However, in openBIS only 21 samples appear and not run (I guess run is written at the end). So the mapping is not working:

> INFO 2018/11/01 14:00:02: <module>() 194: 	-----------Mapping session starting------------
> -----------Mapping session starting------------
> INFO 2018/11/01 14:00:02: general_mapping() 47: 	Mapping called for project antibodies
> Mapping called for project antibodies
> INFO 2018/11/01 14:00:02: general_mapping() 53: 	We are here in project ANTIBODIES
> We are here in project ANTIBODIES
> INFO 2018/11/01 14:00:08: general_mapping() 82: 	Found 21 unmapped MISEQ samples in project ANTIBODIES
> Found 21 unmapped MISEQ samples in project ANTIBODIES
> INFO 2018/11/01 14:00:08: flush() 37: 	0%|          | 0/21 [00:00<?, ?it/s]
> 0%|          | 0/21 [00:00<?, ?it/s]

I don't know of other log files on nevoso.

**Comment by mihuber** [comment]
The work around was to delete the unmapped samples on openBIS and let the resistance samples be analyzed, then upload the samples again from MiSeq.

**Comment by mihuber** [comment]
Update: I created the object _MISEQ_RUN_SAMPLE_ `181025_M02081_0335_000000000-C5N2B_ANTIBODIES` manually. All samples could now be matched and the script proceeds from project _ANTIBODIES_ also to the other projects. About 50 samples of run `181025` are though still missing in openBIS.

**Comment by mihuber** [comment]
Explanation from Lars Malmstroem for the not registered samples :
> It is really hard to tell, I think this is the second time I see this this year. I think it happens when the communication between the dataset server and the application server goes wrong and the dataset server, incorrectly, adds the datasets to a file called .faulty_paths. They are ignored after that. I just deleted the .fautly_paths file and the datasets were imported. I really wish I had a better error report than this, but I simply don't understand the problem well enough and it happens rarely (your 51 samples, and a single sample earlier this year, out of almost 20'000 imported datasets....).

**Comment by ozagordi** [comment]
The lucky ones!!!
