### ISSUE TITLE
Only two samples are analysed in first round of `mapping_pybis_script.py`

### ISSUE THREAD

**Issue by mihuber** [medvir/DMS#20]
We observed that after new samples are mapped with `mapping_pybis_script.py` only two resistance tests are analysed in the first round (instead of 20 as defined by `analyses_per_run`, line 214). After one hour, in the next round, the next samples are then analysed as expected. `Mapping session finished` and `Analysis session starting` happens within a second according to `pybis_script.log`. Maybe it needs more time in opneBIS to label the samples as mapped that they can be recognised for the analysis. Could one insert a pause of maybe 10 seconds in `mapping_pybis_script.py` before line 202 (fetching all resistance samples that are mapped) to allow for mapping?

**Comment by mihuber** [comment]
Example from `pybis_script.log`:

> INFO 2018/11/21 14:00:07: flush() 37: 	0it [00:00, ?it/s]
> 0it [00:00, ?it/s]
> INFO 2018/11/21 14:00:07: general_mapping() 47: 	Mapping called for project resistance
> Mapping called for project resistance
> INFO 2018/11/21 14:00:07: general_mapping() 53: 	We are here in project RESISTANCE
> We are here in project RESISTANCE
> INFO 2018/11/21 14:00:14: general_mapping() 82: 	Found 4 unmapped MISEQ samples in project RESISTANCE
> Found 4 unmapped MISEQ samples in project RESISTANCE
> INFO 2018/11/21 14:00:14: flush() 37: 	0%|          | 0/4 [00:00<?, ?it/s]
> 0%|          | 0/4 [00:00<?, ?it/s]
> INFO 2018/11/21 14:00:20: flush() 37: 	100%|##########| 4/4 [00:05<00:00,  1.38s/it]
> 100%|##########| 4/4 [00:05<00:00,  1.38s/it]
> INFO 2018/11/21 14:00:20: general_mapping() 47: 	Mapping called for project metagenomics
> Mapping called for project metagenomics
> INFO 2018/11/21 14:00:20: general_mapping() 53: 	We are here in project METAGENOMICS
> We are here in project METAGENOMICS
> INFO 2018/11/21 14:00:25: general_mapping() 82: 	Found 0 unmapped MISEQ samples in project METAGENOMICS
> Found 0 unmapped MISEQ samples in project METAGENOMICS
> INFO 2018/11/21 14:00:25: flush() 37: 	0it [00:00, ?it/s]
> 0it [00:00, ?it/s]
> INFO 2018/11/21 14:00:25: general_mapping() 47: 	Mapping called for project plasmids
> Mapping called for project plasmids
> INFO 2018/11/21 14:00:25: general_mapping() 53: 	We are here in project PLASMIDS
> We are here in project PLASMIDS
> INFO 2018/11/21 14:00:31: general_mapping() 82: 	Found 0 unmapped MISEQ samples in project PLASMIDS
> Found 0 unmapped MISEQ samples in project PLASMIDS
> INFO 2018/11/21 14:00:31: flush() 37: 	0it [00:00, ?it/s]
> 0it [00:00, ?it/s]
> INFO 2018/11/21 14:00:31: general_mapping() 47: 	Mapping called for project other
> Mapping called for project other
> INFO 2018/11/21 14:00:31: general_mapping() 53: 	We are here in project OTHER
> We are here in project OTHER
> INFO 2018/11/21 14:00:37: general_mapping() 82: 	Found 16 unmapped MISEQ samples in project OTHER
> Found 16 unmapped MISEQ samples in project OTHER
> INFO 2018/11/21 14:00:37: flush() 37: 	0%|          | 0/16 [00:00<?, ?it/s]
> 0%|          | 0/16 [00:00<?, ?it/s]
> INFO 2018/11/21 14:00:45: flush() 37: 	100%|##########| 16/16 [00:08<00:00,  1.82it/s]
> 100%|##########| 16/16 [00:08<00:00,  1.82it/s]
> INFO 2018/11/21 14:00:45: <module>() 197: 	-----------Mapping session finished------------
> -----------Mapping session finished------------
> INFO 2018/11/21 14:00:45: <module>() 198: 	* * * * * * * * * * * * * * * * * * * * * * * *
> * * * * * * * * * * * * * * * * * * * * * * * *
> INFO 2018/11/21 14:00:45: <module>() 199: 	-----------Analysis session starting-----------
> -----------Analysis session starting-----------
> INFO 2018/11/21 14:00:47: <module>() 211: 	Found 1445 mapped samples
> Found 1445 mapped samples
> INFO 2018/11/21 14:00:47: <module>() 212: 	Found 1443 analysed samples
> Found 1443 analysed samples
> INFO 2018/11/21 14:00:47: <module>() 215: 	Analysis will proceed on 2 samples
> Analysis will proceed on 2 samples
> INFO 2018/11/21 14:00:47: flush() 37: 	0%|          | 0/2 [00:00<?, ?it/s]
> 0%|          | 0/2 [00:00<?, ?it/s]
> INFO 2018/11/21 14:00:47: <module>() 230: 	Datasets found. Sample: 181120_M02081_0341_000000000-C6PDJ-3_RESISTANCE - virus: HIV-1
> Datasets found. Sample: 181120_M02081_0341_000000000-C6PDJ-3_RESISTANCE - virus: HIV-1
> INFO 2018/11/21 14:00:48: run_exe() 144: 	running minvar in /tmp/tmp330tyw5v
> running minvar in /tmp/tmp330tyw5v
> INFO 2018/11/21 14:02:45: run_exe() 160: 	minvar finished, copying files
> minvar finished, copying files
> INFO 2018/11/21 14:02:46: run_exe() 144: 	running v3seq in /tmp/tmpqqryvouf
> running v3seq in /tmp/tmpqqryvouf
> INFO 2018/11/21 14:04:07: run_exe() 160: 	v3seq finished, copying files
> v3seq finished, copying files
> WARNING 2018/11/21 14:04:07: run_exe() 163: 	v3seq finished with an error, saving v3seq.err
> v3seq finished with an error, saving v3seq.err
> INFO 2018/11/21 14:04:08: flush() 37: 	50%|#####     | 1/2 [03:20<03:20, 200.95s/it]
> 50%|#####     | 1/2 [03:20<03:20, 200.95s/it]
> INFO 2018/11/21 14:04:08: <module>() 230: 	Datasets found. Sample: 181120_M02081_0341_000000000-C6PDJ-2_RESISTANCE - virus: HIV-1
> Datasets found. Sample: 181120_M02081_0341_000000000-C6PDJ-2_RESISTANCE - virus: HIV-1
> INFO 2018/11/21 14:04:09: run_exe() 144: 	running minvar in /tmp/tmpmvav4prz
> running minvar in /tmp/tmpmvav4prz
> INFO 2018/11/21 14:06:31: run_exe() 160: 	minvar finished, copying files
> minvar finished, copying files
> INFO 2018/11/21 14:06:31: run_exe() 144: 	running v3seq in /tmp/tmpu1x3177j
> running v3seq in /tmp/tmpu1x3177j
> INFO 2018/11/21 14:07:45: run_exe() 160: 	v3seq finished, copying files
> v3seq finished, copying files
> WARNING 2018/11/21 14:07:45: run_exe() 163: 	v3seq finished with an error, saving v3seq.err
> v3seq finished with an error, saving v3seq.err
> INFO 2018/11/21 14:07:46: flush() 37: 	100%|##########| 2/2 [06:59<00:00, 209.55s/it]
> 100%|##########| 2/2 [06:59<00:00, 209.55s/it]
> INFO 2018/11/21 14:07:46: <module>() 278: 	-----------Analysis session finished-----------
> -----------Analysis session finished-----------

**Comment by ozagordi** [comment]
Command `time.sleep()` is there for you. But:

- I would wait for more than 10 seconds;
- I would ask people at S3IT on why this happens: it negates at least a couple of letters in [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science)).
