### ISSUE TITLE
Further checks in the sample sheet templates

### ISSUE THREAD

**Issue by ozagordi** [medvir/DMS#5]
Is there a check in the Excel templates that enforces presence of number in the first column of the `Data` section? Are they forced to be consecutive?

**Comment by sschmutz** [comment]
When the Makro "SampleSheet überprüfen" is used, it'll check if the value of the first column of the Data section (Sample_ID) is a whole number between 1 and 96. That only applies to the resistance template.
Anyway, the User has never the right to change that field. As soon as there's a value in the Sample Name field, the Sample_ID is filled out automatically.

In case of the research template, the user has all the rights and power. No checks are included there.
