### ISSUE TITLE
Sample Sheet Name

### ISSUE THREAD

**Issue by mihuber** [medvir/DMS#6]
It would be good the also save the name of the sample sheet in openBIS. Would need a new field "SampleSheet" in MISEQ_RUN. The info is saved in MiSeqOutput/RUN_NAME/runParameters.xlm as \<SampleSheetName\>.

**Comment by ozagordi** [comment]
I cannot edit the sample type, I asked the support. BTW, a property Sample Sheet Name exists already in openBIS.

**Comment by mihuber** [comment]
True, the property 'Sample Sheet Name' already exists, but the script does not save the name.

**Comment by ozagordi** [comment]
@mihuber 
Is this still a thing?

**Comment by mihuber** [comment]
Yes, I still think it would be good to save the name. The property exists and the script retrieves the name, but the script does not save the name.
