### ISSUE TITLE
Add property APL (Arbeitsplatzliste) to RESISTANCE_TEST

### ISSUE THREAD

**Issue by mihuber** [medvir/DMS#9]
As wished by Diagnostics, the APL should be added to each RESISTANCE_TEST. The property has already been created in openBIS by Rostik.

- [x] Stefan: Could you please include it in the SampleSheet template for every sample
- [ ] Osvaldo: Needs to be added in the SampleSheet2openBIS.sh script.
- [x] Michael: add to protocol

Thanks
Michael

**Comment by sschmutz** [comment]
I'll add a column next to `timavo` which I'll name `apl`, ok?
Which format does the APL have, should I include a test which checks the APL for validity?

**Comment by mihuber** [comment]
- In the excel template (worksheet Sample Namen) I would add it as "APL" between Sample Name und Virus.
- In the sample sheet (worksheet MiSeq SampleSheet) you can add it at the end next to timavo as "alp". I don't remember if position is important for the SampleSheet2openBIS.sh script.
- Leave as free text at the moment, format may change.
- Yes, stays empty for non diagnostic samples.

**Comment by sschmutz** [comment]
Done. It needs to be described in the Avor.
